# Generated by Django 3.1.5 on 2021-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='links',
            field=models.IntegerField(default=0),
        ),
    ]
