# Generated by Django 3.1.5 on 2021-05-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk', '0002_auto_20210531_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='dir',
        ),
    ]
